ALTER TABLE LISTINGS
DROP CONSTRAINT LISTINGS_UNIQUE_FIELDS,
ADD CONSTRAINT LISTINGS_UNIQUE_FIELDS UNIQUE (TRADE_STATE, AUCTION_HOUSE, SELLER, METADATA, PRICE, TOKEN_SIZE, TRADE_STATE_BUMP);

ALTER TABLE OFFERS
DROP CONSTRAINT OFFERS_UNIQUE_FIELDS,
ADD CONSTRAINT OFFERS_UNIQUE_FIELDS UNIQUE (TRADE_STATE, AUCTION_HOUSE, BUYER, METADATA, PRICE, TOKEN_SIZE, TRADE_STATE_BUMP);