CREATE TABLE hpl_reward_center_execute_sale_ins (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    buyer varchar(48) NOT NULL,
    buyer_reward_token_account varchar(48) NOT NULL,
    seller varchar(48) NOT NULL,
    seller_reward_token_account varchar(48) NOT NULL,
    listing varchar(48) NOT NULL,
    offer varchar(48) NOT NULL,
    payer varchar(48) NOT NULL,
    token_account varchar(48) NOT NULL,
    token_mint varchar(48) NOT NULL,
    metadata varchar(48) NOT NULL,
    treasury_mint varchar(48) NOT NULL,
    seller_payment_receipt_account varchar(48) NOT NULL,
    buyer_receipt_token_account varchar(48) NOT NULL,
    authority varchar(48) NOT NULL,
    escrow_payment_account varchar(48) NOT NULL,
    auction_house varchar(48) NOT NULL,
    auction_house_fee_account varchar(48) NOT NULL,
    auction_house_treasury varchar(48) NOT NULL,
    buyer_trade_state varchar(48) NOT NULL,
    seller_trade_state varchar(48) NOT NULL,
    free_trade_state varchar(48) NOT NULL,
    reward_center varchar(48) NOT NULL,
    reward_center_reward_token_account varchar(48) NOT NULL,
    ah_auctioneer_pda varchar(48) NOT NULL,
    escrow_payment_bump smallint NOT NULL,
    free_trade_state_bump smallint NOT NULL,
    program_as_signer_bump smallint NOT NULL,
    created_at timestamp NOT NULL,
    slot bigint NOT NULL
);

CREATE TABLE hpl_reward_center_close_offer_ins (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    wallet varchar(48) NOT NULL,
    offer varchar(48) NOT NULL,
    treasury_mint varchar(48) NOT NULL,
    token_account varchar(48) NOT NULL,
    receipt_account varchar(48) NOT NULL,
    escrow_payment_account varchar(48) NOT NULL,
    metadata varchar(48) NOT NULL,
    token_mint varchar(48) NOT NULL,
    authority varchar(48) NOT NULL,
    reward_center varchar(48) NOT NULL,
    auction_house varchar(48) NOT NULL,
    auction_house_fee_account varchar(48) NOT NULL,
    trade_state varchar(48) NOT NULL,
    ah_auctioneer_pda varchar(48) NOT NULL,
    escrow_payment_bump smallint NOT NULL,
    buyer_price bigint NOT NULL,
    token_size bigint NOT NULL,
    created_at timestamp NOT NULL,
    slot bigint NOT NULL
);

CREATE TABLE hpl_reward_center_close_listing_ins (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid (),
    wallet varchar(48) NOT NULL,
    listing varchar(48) NOT NULL,
    metadata varchar(48) NOT NULL,
    token_account varchar(48) NOT NULL,
    token_mint varchar(48) NOT NULL,
    authority varchar(48) NOT NULL,
    reward_center varchar(48) NOT NULL,
    auction_house varchar(48) NOT NULL,
    auction_house_fee_account varchar(48) NOT NULL,
    trade_state varchar(48) NOT NULL,
    ah_auctioneer_pda varchar(48) NOT NULL,
    token_size bigint NOT NULL,
    created_at timestamp NOT NULL,
    slot bigint NOT NULL
);

