ALTER TABLE listings
    ADD COLUMN active bool not null GENERATED ALWAYS AS 
    (purchase_id is  null and canceled_at is  null) 
	STORED;


ALTER TABLE offers
    ADD COLUMN active bool not null GENERATED ALWAYS AS 
    (purchase_id is  null and canceled_at is  null) 
	STORED;


ALTER TABLE LISTINGS
DROP CONSTRAINT LISTINGS_UNIQUE_FIELDS,
ADD CONSTRAINT LISTINGS_UNIQUE_FIELDS UNIQUE (TRADE_STATE, AUCTION_HOUSE, SELLER, METADATA, PRICE, TOKEN_SIZE, TRADE_STATE_BUMP, ACTIVE);

ALTER TABLE OFFERS
DROP CONSTRAINT OFFERS_UNIQUE_FIELDS,
ADD CONSTRAINT OFFERS_UNIQUE_FIELDS UNIQUE (TRADE_STATE, AUCTION_HOUSE, BUYER, METADATA, PRICE, TOKEN_SIZE, TRADE_STATE_BUMP, ACTIVE);