ALTER TABLE COLLECTION_TRENDS DROP COLUMN _1D_MARKETCAP;
ALTER TABLE COLLECTION_TRENDS DROP COLUMN PREV_1D_MARKETCAP;
ALTER TABLE COLLECTION_TRENDS DROP COLUMN _7D_MARKETCAP;
ALTER TABLE COLLECTION_TRENDS DROP COLUMN PREV_7D_MARKETCAP;
ALTER TABLE COLLECTION_TRENDS DROP COLUMN _30D_MARKETCAP;
ALTER TABLE COLLECTION_TRENDS DROP COLUMN PREV_30D_MARKETCAP;
ALTER TABLE COLLECTION_TRENDS DROP COLUMN NFT_COUNT;