ALTER TABLE COLLECTION_TRENDS
    ADD COLUMN _1D_MARKETCAP NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN PREV_1D_MARKETCAP NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN _7D_MARKETCAP NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN PREV_7D_MARKETCAP NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN _30D_MARKETCAP NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN PREV_30D_MARKETCAP NUMERIC NOT NULL DEFAULT 0,
    ADD COLUMN NFT_COUNT bigint NOT NULL DEFAULT 0;
    
ALTER TABLE COLLECTION_TRENDS
    ADD COLUMN _1d_marketcap_change BIGINT GENERATED ALWAYS AS 
    (coalesce(100*( NULLIF(_1D_marketcap,0) - NULLIF(PREV_1D_marketcap,0) ) / NULLIF(PREV_1D_marketcap,0), 0)) 
	STORED,
    ADD COLUMN _7d_marketcap_change BIGINT GENERATED ALWAYS AS 
    (coalesce(100*( NULLIF(_7D_marketcap,0) - NULLIF(PREV_7D_marketcap,0) ) / NULLIF(PREV_7D_marketcap,0), 0)) 
	STORED,
    ADD COLUMN _30d_marketcap_change BIGINT GENERATED ALWAYS AS 
    (coalesce(100*( NULLIF(_30D_marketcap,0) - NULLIF(PREV_30D_marketcap,0) ) / NULLIF(PREV_30D_marketcap,0), 0))
	STORED;

