drop table buy_instructions;
drop table sell_instructions;
drop table execute_sale_instructions;
drop table cancel_instructions;
drop table deposit_instructions;
drop table withdraw_instructions;
drop table withdraw_from_fee_instructions;
drop table withdraw_from_treasury_instructions;
drop table public_buy_instructions;