WITH VOLUME AS
	(SELECT METADATA_COLLECTION_KEYS.COLLECTION_ADDRESS AS COLLECTION,
			SUM(PURCHASES.PRICE)::numeric AS _30D_VOLUME
		FROM PURCHASES
		INNER JOIN METADATA_COLLECTION_KEYS ON (METADATA_COLLECTION_KEYS.METADATA_ADDRESS = PURCHASES.METADATA)
		WHERE PURCHASES.CREATED_AT >= (NOW() - INTERVAL '30 days')
		GROUP BY COLLECTION_ADDRESS)
UPDATE COLLECTIONS_VOLUME
SET _30D_VOLUME = V._30D_VOLUME
FROM VOLUME V
INNER JOIN COLLECTIONS_VOLUME CV ON V.COLLECTION = CV.COLLECTION
WHERE COLLECTIONS_VOLUME.collection = CV.collection;

WITH VOLUME AS
	(SELECT me_metadata_collections.collection_id::text as collection, SUM(purchases.price)::numeric as _30D_VOLUME
    FROM purchases
    INNER JOIN me_metadata_collections ON (me_metadata_collections.metadata_address = purchases.metadata)
    WHERE PURCHASES.CREATED_AT >= (NOW() - INTERVAL '30 days')
    AND purchases.marketplace_program = 'M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K'
    GROUP BY collection_id)
UPDATE COLLECTIONS_VOLUME
SET _30D_VOLUME = V._30D_VOLUME
FROM VOLUME V
INNER JOIN COLLECTIONS_VOLUME CV ON V.COLLECTION = CV.COLLECTION
WHERE COLLECTIONS_VOLUME.collection = CV.collection;

WITH VOLUME AS
	(SELECT METADATA_COLLECTION_KEYS.COLLECTION_ADDRESS AS COLLECTION,
			SUM(PURCHASES.PRICE)::numeric AS _prev_30d_volume
		FROM PURCHASES
		INNER JOIN METADATA_COLLECTION_KEYS ON (METADATA_COLLECTION_KEYS.METADATA_ADDRESS = PURCHASES.METADATA)
		WHERE PURCHASES.CREATED_AT >= (NOW() - INTERVAL '2 months') AND PURCHASES.CREATED_AT <= (NOW() - INTERVAL '1 months')
		GROUP BY COLLECTION_ADDRESS)
UPDATE COLLECTIONS_VOLUME
SET _prev_30d_volume = V._prev_30d_volume
FROM VOLUME V
INNER JOIN COLLECTIONS_VOLUME CV ON V.COLLECTION = CV.COLLECTION
WHERE COLLECTIONS_VOLUME.collection = CV.collection;

WITH VOLUME AS
	(SELECT me_metadata_collections.collection_id::text as collection, SUM(purchases.price)::numeric as _prev_30d_volume
    FROM purchases
    INNER JOIN me_metadata_collections ON (me_metadata_collections.metadata_address = purchases.metadata)
    WHERE PURCHASES.CREATED_AT >= (NOW() - INTERVAL '2 months') AND PURCHASES.CREATED_AT <= (NOW() - INTERVAL '1 months')
    AND purchases.marketplace_program = 'M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K'
    GROUP BY collection_id)
UPDATE COLLECTIONS_VOLUME
SET _prev_30d_volume = V._prev_30d_volume
FROM VOLUME V
INNER JOIN COLLECTIONS_VOLUME CV ON V.COLLECTION = CV.COLLECTION
WHERE COLLECTIONS_VOLUME.collection = CV.collection;