create view collection_count as
select count(metadata_collection_keys.metadata_address) as nft_count from metadata_collection_keys
where metadata_collection_keys.verified = true
group by metadata_collection_keys.collection_address;