BEGIN WORK;
DO $$
BEGIN
  	IF (SELECT NOT EXISTS (SELECT 1 FROM information_schema.tables  WHERE table_schema = 'public' AND table_name = 'me_collections')) THEN
	CREATE TABLE TEMP_ME_COLLECTIONS AS
	(SELECT DISTINCT M.SYMBOL,
			MC.CREATOR_ADDRESS,
			T.NAME,
			T.FAMILY
		FROM METADATAS M
		INNER JOIN METADATA_CREATORS MC ON MC.METADATA_ADDRESS = M.ADDRESS
		INNER JOIN PURCHASES P ON P.METADATA = M.ADDRESS
		LEFT JOIN METADATA_COLLECTIONS T ON T.METADATA_ADDRESS = M.ADDRESS
		WHERE P.MARKETPLACE_PROGRAM = 'M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K'
			AND MC.VERIFIED = TRUE
			AND MC.POSITION = 0
		GROUP BY (M.SYMBOL, MC.CREATOR_ADDRESS, T.NAME, T.FAMILY)
		HAVING COUNT(*) >= 100);
	
	DELETE FROM TEMP_ME_COLLECTIONS WHERE SYMBOL = '' AND NAME IS NULL AND FAMILY IS NULL;

	ALTER TABLE TEMP_ME_COLLECTIONS ADD COLUMN ID UUID DEFAULT '00000000-0000-0000-0000-000000000000';
	
	UPDATE TEMP_ME_COLLECTIONS SET ID = MD5_ID FROM 
		(SELECT MD5(T::TEXT)::UUID AS MD5_ID, SYMBOL, NAME, FAMILY FROM TEMP_ME_COLLECTIONS T) T 
		WHERE 
		TEMP_ME_COLLECTIONS.SYMBOL IS NOT NULL AND TEMP_ME_COLLECTIONS.NAME IS NOT NULL
		AND TEMP_ME_COLLECTIONS.NAME = T.NAME AND 
		TEMP_ME_COLLECTIONS.FAMILY IS NOT DISTINCT FROM T.FAMILY 
		AND TEMP_ME_COLLECTIONS.SYMBOL = T.SYMBOL;
	
	UPDATE TEMP_ME_COLLECTIONS SET ID = MD5_ID FROM 
		(SELECT MD5(T::TEXT)::UUID AS MD5_ID, T.* FROM TEMP_ME_COLLECTIONS T 
		WHERE T.NAME IS NULL AND T.FAMILY IS NULL) T 
		WHERE 
		TEMP_ME_COLLECTIONS.FAMILY IS NULL AND TEMP_ME_COLLECTIONS.NAME IS NULL 
		AND TEMP_ME_COLLECTIONS.SYMBOL = T.SYMBOL AND T.CREATOR_ADDRESS = TEMP_ME_COLLECTIONS.CREATOR_ADDRESS;

	ALTER TABLE TEMP_ME_COLLECTIONS ADD PRIMARY KEY (CREATOR_ADDRESS, ID);
	
	CREATE TABLE TEMP_ME_METADATA_COLLECTIONS AS
		(SELECT M.ADDRESS AS METADATA_ADDRESS,
				C.ID AS COLLECTION_ID
			FROM TEMP_ME_COLLECTIONS C
			INNER JOIN METADATA_CREATORS MC ON MC.CREATOR_ADDRESS = C.CREATOR_ADDRESS
			INNER JOIN METADATAS M ON M.ADDRESS = MC.METADATA_ADDRESS
			AND M.SYMBOL = C.SYMBOL
			INNER JOIN METADATA_COLLECTIONS TC ON TC.METADATA_ADDRESS = M.ADDRESS
			AND TC.NAME IS NOT DISTINCT
			FROM C.NAME
			AND TC.FAMILY IS NOT DISTINCT
			FROM C.FAMILY);
	ALTER TABLE TEMP_ME_METADATA_COLLECTIONS REPLICA IDENTITY FULL;

	DELETE
	FROM TEMP_ME_METADATA_COLLECTIONS
	WHERE METADATA_ADDRESS in
			(SELECT METADATA_ADDRESS
				FROM METADATA_COLLECTION_KEYS);

	DELETE
	FROM TEMP_ME_COLLECTIONS
	WHERE ID in
			(SELECT MC.ID
				FROM TEMP_ME_COLLECTIONS MC
				LEFT JOIN TEMP_ME_METADATA_COLLECTIONS T ON MC.ID = T.COLLECTION_ID
				WHERE T.COLLECTION_ID IS NULL);

	DROP TABLE IF EXISTS ME_METADATA_COLLECTIONS;

	CREATE TABLE ME_METADATA_COLLECTIONS AS
		(SELECT DISTINCT *
			FROM TEMP_ME_METADATA_COLLECTIONS);

	ALTER TABLE ME_METADATA_COLLECTIONS ADD PRIMARY KEY (METADATA_ADDRESS, COLLECTION_ID);
	
	CREATE TABLE TEMP_ME_COLLECTIONS_2 as (select distinct symbol, name, family, id from temp_me_collections);
	
	ALTER TABLE TEMP_ME_COLLECTIONS_2 ADD PRIMARY KEY (ID);
	
	DROP TABLE TEMP_ME_COLLECTIONS;

	DROP TABLE IF EXISTS ME_COLLECTIONS;

	ALTER TABLE TEMP_ME_COLLECTIONS_2 RENAME TO ME_COLLECTIONS;

	DROP TABLE TEMP_ME_METADATA_COLLECTIONS;
	
	-- add image col to me_collections table

	ALTER TABLE ME_COLLECTIONS ADD COLUMN IMAGE TEXT NOT NULL DEFAULT '';

	UPDATE ME_COLLECTIONS
	SET IMAGE = M.IMAGE
	FROM
		(SELECT C.ID AS COLLECTION_ID,
				MJ.IMAGE AS IMAGE
			FROM ME_COLLECTIONS C
			INNER JOIN ME_METADATA_COLLECTIONS MC1 ON MC1.METADATA_ADDRESS =
				(SELECT METADATA_ADDRESS
					FROM ME_METADATA_COLLECTIONS MC2
					WHERE C.ID = MC2.COLLECTION_ID
					LIMIT 1)
			INNER JOIN METADATA_JSONS MJ ON MJ.METADATA_ADDRESS = MC1.METADATA_ADDRESS) M
	WHERE ME_COLLECTIONS.ID = M.COLLECTION_ID;
	END IF;
END $$;
COMMIT WORK;