ALTER TABLE COLLECTIONS_VOLUME
    ADD COLUMN _1D_FLOOR_PRICE NUMERIC DEFAULT 0,
    ADD COLUMN PREV_1D_FLOOR_PRICE NUMERIC DEFAULT 0,
    ADD COLUMN _1D_SALES_COUNT NUMERIC DEFAULT 0,
    ADD COLUMN PREV_1D_SALES_COUNT NUMERIC DEFAULT 0,
    ADD COLUMN _7D_FLOOR_PRICE NUMERIC DEFAULT 0,
    ADD COLUMN PREV_7D_FLOOR_PRICE NUMERIC DEFAULT 0,
    ADD COLUMN _7D_SALES_COUNT NUMERIC DEFAULT 0,
    ADD COLUMN PREV_7D_SALES_COUNT NUMERIC DEFAULT 0,
    ADD COLUMN _30D_FLOOR_PRICE NUMERIC DEFAULT 0,
    ADD COLUMN PREV_30D_FLOOR_PRICE NUMERIC DEFAULT 0,
    ADD COLUMN _30D_SALES_COUNT NUMERIC DEFAULT 0,
    ADD COLUMN PREV_30D_SALES_COUNT NUMERIC DEFAULT 0;

ALTER TABLE COLLECTIONS_VOLUME RENAME TO COLLECTION_TRENDS;

UPDATE COLLECTION_TRENDS SET _1D_VOLUME = 0 WHERE _1D_VOLUME IS NULL;
UPDATE COLLECTION_TRENDS SET _7D_VOLUME = 0 WHERE _7D_VOLUME IS NULL;
UPDATE COLLECTION_TRENDS SET _30D_VOLUME = 0 WHERE _30D_VOLUME IS NULL;
UPDATE COLLECTION_TRENDS SET _PREV_1D_VOLUME = 0 WHERE _PREV_1D_VOLUME IS NULL;
UPDATE COLLECTION_TRENDS SET _PREV_7D_VOLUME = 0 WHERE _PREV_7D_VOLUME IS NULL;
UPDATE COLLECTION_TRENDS SET _PREV_30D_VOLUME = 0 WHERE _PREV_30D_VOLUME IS NULL;

ALTER TABLE COLLECTION_TRENDS ALTER COLUMN _1D_VOLUME SET DEFAULT 0,
    ALTER COLUMN _7D_VOLUME SET DEFAULT 0,
    ALTER COLUMN _1D_VOLUME SET DEFAULT 0,
    ALTER COLUMN _30D_VOLUME SET DEFAULT 0,
    ALTER COLUMN _PREV_1D_VOLUME SET DEFAULT 0,
    ALTER COLUMN _PREV_7D_VOLUME SET DEFAULT 0,
    ALTER COLUMN _PREV_30D_VOLUME SET DEFAULT 0;
