apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: geyser-consumer
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: geyser-consumer
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: geyser-consumer
    spec:
      containers:
      - name: geyser-consumer
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:geyser-consumer-actions-kube-poc-f7f4c4b
        env:
        - name: AMPQ_URL
          valueFrom:
            secretKeyRef:
              name: ampq-creds
              key: AMPQ_URL
              optional: false
        - name: DATABASE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: DATABASE_WRITE_URL
              optional: false
        - name: LOG_LEVEL
          value: debug
        command: ["/bin/bash","-c"]
        args: ["export $(cat .env | xargs)  && RUST_LOG=$LOG_LEVEL ./bin/holaplex-indexer-geyser --network=mainnet --startup=all kube & RUST_LOG=$LOG_LEVEL ./bin/holaplex-indexer-geyser --network=mainnet --startup=normal kube"]
        volumeMounts:
        - name: indexer-config
          mountPath: .env
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
      dnsConfig:
        options:
        - name: ndots
          value: "3"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: indexer-config
          configMap:
            name: indexer-config
