apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: graphql
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: 011737333588.dkr.ecr.us-east-1.amazonaws.com/indexer:graphql-actions-kube-poc-f7f4c4b
        env:
        - name: DATABASE_READ_URL
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: DATABASE_READ_URL
              optional: false
        - name: TWITTER_BEARER_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-creds
              key: TWITTER_BEARER_TOKEN
              optional: false
        command: ["./bin/holaplex-indexer-graphql"]
        volumeMounts:
        - name: indexer-config
          mountPath: .env.local
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: indexer-config
          configMap:
            name: indexer-config
---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '300'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:011737333588:certificate/ab1fb583-a6e3-47bc-9f18-6b7e2ab5587d
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  selector:
    app: graphql
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  type: LoadBalancer
