name: Check crate feature flags

on:
  schedule:
    - cron: '0 1,9 * * *'

jobs:
  check:
    name: check flags
    runs-on: indexer-test-runner
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-11-09
          components: cargo, rustc
          profile: minimal

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', 'rust-toolchain.toml') }}-cf

      - name: run checks
        run: |
          scripts/check-features.sh

